theme: jekyll-theme-cayman
title: DIR2025
email: heydar.soudani@ru.nl
description: >- # this means to ignore newlines until "baseurl:"
 DIR2025
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: HeydarSoudani
